SCENARIOS = [
    {
        "name": "Normal Shipment",
        "description": "Clean shipment with no anomalies",
        "data": {
            "shipment_id": "SHP001",
            "commodity": "electronics",
            "temperature_celsius": 22,
            "weight_kg": 1000,
            "volume_cbm": 10,
            "igm_quantity": 100,
            "bol_quantity": 100,
            "invoice_quantity": 100,
            "igm_value": 50000,
            "bol_value": 50000,
            "invoice_value": 50000,
            "actual_origin_country": "China",
            "declared_origin_country": "China",
            "burst_count": 1,
            "submission_hour": 14,
            "account_age_days": 365,
            "company_trust_score": 85,
            "kyc_verified": 1,
            "linked_company_id": None,
            "shared_director_flag": 0,
            "is_anomalous": 0,
        },
    },
    {
        "name": "Origin Fraud",
        "description": "Misdeclared origin country",
        "data": {
            "shipment_id": "SHP002",
            "commodity": "textiles",
            "temperature_celsius": 25,
            "weight_kg": 500,
            "volume_cbm": 5,
            "igm_quantity": 50,
            "bol_quantity": 50,
            "invoice_quantity": 50,
            "igm_value": 20000,
            "bol_value": 20000,
            "invoice_value": 20000,
            "actual_origin_country": "North Korea",
            "declared_origin_country": "Vietnam",
            "burst_count": 3,
            "submission_hour": 3,
            "account_age_days": 45,
            "company_trust_score": 40,
            "kyc_verified": 0,
            "linked_company_id": "COMP_SUSPICIOUS",
            "shared_director_flag": 1,
            "is_anomalous": 1,
        },
    },
    {
        "name": "Document Mismatch",
        "description": "Quantity and value discrepancies",
        "data": {
            "shipment_id": "SHP003",
            "commodity": "gold",
            "temperature_celsius": 20,
            "weight_kg": 50,
            "volume_cbm": 0.5,
            "igm_quantity": 100,
            "bol_quantity": 85,
            "invoice_quantity": 120,
            "igm_value": 500000,
            "bol_value": 425000,
            "invoice_value": 600000,
            "actual_origin_country": "UAE",
            "declared_origin_country": "UAE",
            "burst_count": 8,
            "submission_hour": 2,
            "account_age_days": 15,
            "company_trust_score": 25,
            "kyc_verified": 0,
            "linked_company_id": None,
            "shared_director_flag": 0,
            "is_anomalous": 1,
        },
    },
    {
        "name": "Physics Impossible",
        "description": "Bananas stored at freezing temperature",
        "data": {
            "shipment_id": "SHP004",
            "commodity": "bananas",
            "temperature_celsius": -18,
            "weight_kg": 2000,
            "volume_cbm": 20,
            "igm_quantity": 200,
            "bol_quantity": 200,
            "invoice_quantity": 200,
            "igm_value": 10000,
            "bol_value": 10000,
            "invoice_value": 10000,
            "actual_origin_country": "Ecuador",
            "declared_origin_country": "Ecuador",
            "burst_count": 2,
            "submission_hour": 10,
            "account_age_days": 200,
            "company_trust_score": 70,
            "kyc_verified": 1,
            "linked_company_id": None,
            "shared_director_flag": 0,
            "is_anomalous": 1,
        },
    },
    {
        "name": "Network Fraud",
        "description": "Linked to known fraudulent entities",
        "data": {
            "shipment_id": "SHP005",
            "commodity": "electronics",
            "temperature_celsius": 22,
            "weight_kg": 800,
            "volume_cbm": 8,
            "igm_quantity": 80,
            "bol_quantity": 80,
            "invoice_quantity": 80,
            "igm_value": 40000,
            "bol_value": 40000,
            "invoice_value": 40000,
            "actual_origin_country": "Singapore",
            "declared_origin_country": "Singapore",
            "burst_count": 1,
            "submission_hour": 9,
            "account_age_days": 500,
            "company_trust_score": 60,
            "kyc_verified": 1,
            "linked_company_id": "COMP_FRAUD_001",
            "shared_director_flag": 1,
            "is_anomalous": 1,
        },
    },
]
